name: Build
on: [push]
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: "Check out code"
        uses: actions/checkout@v3
      - name: "Set up Go"
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.x
      - name: build examples
        run: |
          sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d
          ./bin/task setup
          ./bin/task examples
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18.x
      - uses: actions/checkout@v3
      - name: lint
        uses: golangci/golangci-lint-action@v3
